---
title: "Paul Fornia"
output:
  html_document: default
  pdf_document: default
---

[LinkedIn](https://www.linkedin.com/in/paulfornia/)

[paulfornia@gmail.com](mailto:paulfornia@gmail.com)

[Resume](./Resume_Fornia_2017_08_30.pdf)

Paul is an experienced analytics and data science consultant serving federal clients in the Washington, DC area. He specializes in bringing powerful statistical and machine learning theory into real situations quickly and practically, implementing easy-to-use tools that enable clients to get measurable value from their existing data.

In addition to a strong foundation in math and statistics, Paul has over 5 years of programming experience in a wide variety of languages, including C++, Java, Python, SAS, SQL, and especially R. He is also familiar with industry-standard tools used in the data science pipeline such as Linux, Git, AWS and Agile processes.

Paul grew up in Denver, CO, and graduated from the University of Colorado at Boulder with degrees in Applied Math and Economics Magna cum laude in 2012. He lives with his wife and furry beagle in Jessup, MD, between Washington and Baltimore. He is an avid skier, hobbyist musician, and aspiring home-improvement DIYer.

## Portfolio 

Here are some non-professional projects that I've put together, mostly for fun or to learn something new.

["Clue-less" Multiplayer Game](https://github.com/pfornia/battleware) ([video explainer](https://www.youtube.com/edit?o=U&video_id=zvuOLRJWVi0)): Python, GUI, OO

[Kaggle Point Calculator](https://github.com/pfornia/kaggle_points_calculator) ([web app](https://paulfornia.shinyapps.io/Data_Products_Project_v2/)): R, Shiny

[Next Word Predictor](https://github.com/pfornia/next_word_predictor) ([web app](https://paulfornia.shinyapps.io/Capstone_v3/)): R, Shiny, NLP

[2048 Console Game](https://github.com/pfornia/Python-Demo-2048): Python

[Caesar Cipher Decrypter](https://github.com/pfornia/Java_Demo_Cipher): Java

[Calculator From Scratch](https://github.com/pfornia/Excel_Demo_Transistor_Calculator): Excel

[Patio](./patio.JPG): Herringbone brick, 225 sqft, Stone firepit w/ built-in grill